### ISSUE TITLE
Clickable elements when exporting to svg

### ISSUE THREAD

**Issue by jeffabailey** [structurizr/puppeteer#11]
How difficult would it be to make this script export a clickable SVG?

https://github.com/structurizr/puppeteer/blob/master/export-diagrams-lite.js#L8

I added a link to a box to a generated SVG, which works when opening it with Google Chrome.

https://www.w3.org/wiki/SVG_Links

If you can point me to structurizr.scripting.exportCurrentDiagramToSVG I can try to edit it. I'm not seeing that functin any repos in this repo's organization.

**Comment by jeffabailey** [comment]
I see.

Is there a reason to skip using the SVG Link standard?

Is it possible to meet a different use case?

I was hoping to generate standalone SVG files with clickable links without embedding them in an HTML file.

**Comment by jeffabailey** [comment]
I'm getting 404s from these URLs, is there an example?

https://structurizr.com/help/scripting-diagrams
https://structurizr.com/help/scripting-documentation

I've created this simple HTML file, and I'm getting the following error.

```
<!DOCTYPE html>
<html>
    <head>
        <script type="application/javascript">
            function structurizrElementDoubleClicked(event,url) {
                console.log('event', event);
                console.log('url', url);
            }
        </script>
    </head>
    <body>
        <object type="image/svg+xml" data="./structurizr-congress.svg"/>
    </body>
</html>
```

```
structurizr-congress.svg:1 Uncaught ReferenceError: structurizrElementDoubleClicked is not defined
    at SVGGElement.ondblclick (structurizr-congress.svg:1:33904)
```

**Comment by simonbrowndotje** [comment]
The SVG export is a cleaned up version of the SVG created by the JavaScript framework used for rendering diagrams (you can inspect a Structurizr diagram via your web browser's developer tools to see this). Since the SVG itself is hosted within a HTML page, JavaScript event handlers are used for the diagram navigation, so that's what the export does too.

A web browser is one of the most ubiquitous SVG viewers out there, so I'm curious as to why you don't want to embed SVG inside HTML.

**Comment by simonbrowndotje** [comment]
The docs are here now -> https://structurizr.com/help/exporting-diagrams#svg

And for an example, sure, you can export any diagram to an offline HTML page and view the source ... it uses the same SVG export mechanism.

**Comment by jeffabailey** [comment]
Thanks!

I can get the events to fire by embedding the raw SVG in the HTML page.

>  I'm curious as to why you don't want to embed SVG inside HTML.

I aim to embed the SVG files in random HTML files without access to change the JavaScript.

**Example:** Confluence pages

**Comment by simonbrowndotje** [comment]
If it's just Confluence, you might investigate building a Confluence macro, because these can easily include JavaScript.

**Comment by jeffabailey** [comment]
It's multiple locations, but I'm good.

Thanks for the help!
