### ISSUE TITLE
Layout not applied when exporting

### ISSUE THREAD

**Issue by eugeneniemand** [structurizr/puppeteer#12]
HI Appreciate this is an old repo. I  hope someone can provide a little help. I have some diagrams manually laid out and some using auto-layout. It seems the manual ones looses the formatting and everything is bunched up in the top left corner but the auto layout ones seem ok. Any ideas?

**Comment by simonbrowndotje** [comment]
The puppeteer scripts in this repo do little more than open your diagrams in a headless browser, and call some JavaScript functions to export them ... so you should see the same results if you open a regular web browser. Is that not the case?

**Comment by simonbrowndotje** [comment]
Closing as stale.
