### ISSUE TITLE
Inconsistent diagrams export

### ISSUE THREAD

**Issue by gravis** [structurizr/puppeteer#15]
### Description

We are conducting an [experiment with Structurizr at GitLab](https://gitlab.com/gitlab-com/gl-security/security-architecture/gitlab-architecture/) to model our different architectures. Recently, we discovered that the diagrams we were exporting using this repo were inconsistent. Some diagrams are replaced by others in the export, leading to unpredictability and duplicates.

I could reproduce with a simple example, so it doesn't seem to be related to our code.

### Steps to reproduce

1. `curl -o https://raw.githubusercontent.com/structurizr/dsl/a97141682dffd8b5104cedd7155e1a87be2d5fb6/src/test/dsl/big-bank-plc.dsl`
2. `docker run -it --rm -p 8080:8080 -v $PWD:/usr/local/structurizr -e STRUCTURIZR_WORKSPACE_PATH=. -d structurizr/lite`
3. `until curl -f -s -o /dev/null http://localhost:8080; do echo -n "."; sleep 1; done`
4. `node export-diagrams.js http://localhost:8080/workspace/diagrams png`

### Screenshot

`Components.png`:

![Components](https://github.com/structurizr/puppeteer/assets/12752/2f5bf58e-3a82-4d6a-972c-a82bd161befc)

`Containers.png`:

![Containers](https://github.com/structurizr/puppeteer/assets/12752/4663be3b-76a8-4898-adc3-faba59c4e031)

(Same files)

Everything seems scrambled. System Landscapes replace Components view, some others appear multiple times.

### Code sample

```text
See https://gitlab.com/gitlab-com/gl-security/security-architecture/gitlab-architecture/-/blob/main/scripts/export-workspaces.sh?ref_type=heads
```

### Configuration

```
Structurizr Lite
 - build: 3216 (2023-11-09T07:28:05Z)
 - structurizr-java: v1.27.0
 - structurizr-dsl: v1.33.0
 - structurizr-import: v1.6.0
 - structurizr-graphviz: v2.2.2
```

(From `package.json`:)
"[puppeteer](https://npmjs.com/package/puppeteer)": "[^20.9.0](https://npmjs.com/package/puppeteer)"
(same result with `21.5.1`).

### Severity

Major

### Priority

I have no budget and there's no rush, please fix this for free

**Comment by gravis** [comment]
This behaviour changed between Oct 18 (https://gitlab.com/gitlab-com/gl-security/security-architecture/gitlab-architecture/-/pipelines/1041454764) and Oct 21 apparently (https://gitlab.com/gitlab-com/gl-security/security-architecture/gitlab-architecture/-/pipelines/1044783745)

**Comment by gravis** [comment]
I can reproduce the bug without using Docker, so I can eliminate that from the equation at least.

**Comment by simonbrowndotje** [comment]
It's related to the changes to how Graphviz is called from the diagram viewer, which requires the Puppeteer script to be rewritten.

**Comment by gravis** [comment]
Thanks for the insights @simonbrowndotje. 
I'm far from being a node/javascript expert, but I think I have isolated the problem in `structurizr.scripting.exportCurrentDiagramToPNG` function, which doesn't export the current diagram, but a random one.

I've simplified the script to:

<details><summary>export_diagram.js</summary>

```javascript
const puppeteer = require('puppeteer');
const fs = require('fs');

const PNG_FORMAT = 'png';
const SVG_FORMAT = 'svg';

const IGNORE_HTTPS_ERRORS = true;
const HEADLESS = true;

const IMAGE_VIEW_TYPE = 'Image';

if (process.argv.length < 4) {
  console.log("Usage: <structurizrUrl> <png|svg> [username] [password]")
  process.exit(1);
}

const url = process.argv[2];
const format = process.argv[3];

if (format !== PNG_FORMAT && format !== SVG_FORMAT) {
  console.log("The output format must be ' + PNG_FORMAT + ' or ' + SVG_FORMAT + '.");
  process.exit(1);
}

(async () => {
  const browser = await puppeteer.launch({ignoreHTTPSErrors: IGNORE_HTTPS_ERRORS, headless: HEADLESS});
  const page = await browser.newPage();

  // visit the diagrams page
  console.log(" - Opening " + url);
  await page.goto(url, { waitUntil: 'domcontentloaded' });
  await page.waitForFunction('structurizr.scripting && structurizr.scripting.isDiagramRendered() === true');

  if (format === PNG_FORMAT) {
    // add a function to the page to save the generated PNG images
    await page.exposeFunction('savePNG', (content, filename) => {
      console.log(" - " + filename);
      content = content.replace(/^data:image\/png;base64,/, "");
      fs.writeFile(filename, content, 'base64', function (err) {
        if (err) throw err;
      });
    });
  }

  // get the array of views
  const views = await page.evaluate(() => {
    return structurizr.scripting.getViews();
  });

  console.log(" - Starting export");
  // for (var i = 0; i < views.length; i++) {
    const view = views[0];
    console.log(" VIEW: " + view.key)

    await page.evaluate((view) => {
      structurizr.scripting.changeView(view.key);
    }, view);

    await page.waitForFunction('structurizr.scripting.isDiagramRendered() === true');

    const diagramFilename = view.key + '.png';

    await page.evaluate((diagramFilename) => {
      structurizr.scripting.exportCurrentDiagramToPNG({ includeMetadata: true, crop: false }, function(png) {
        window.savePNG(png, diagramFilename);
      })
    }, diagramFilename);
    const current_view =  await page.evaluate(() => {
      return structurizr.scripting.getViewKey();
    });

    console.log(" CURRENT_VIEW: " + current_view)
    //if (i == views.length-1) {
        console.log(" - Finished");
        browser.close();
   // }
  //}

})();
```

</details>


<details><summary>output</summary>
- Opening http://localhost:8080/workspace/diagrams
- Starting export
VIEW: SystemLandscape
- SystemLandscape.png
CURRENT_VIEW: SystemLandscape
- Finished
</details>

To export a single file, which should be the SystemLandscape. As you can see in the output, the current view is the SystemLandscape, but the created file is a random diagram.

I don't know if that helps, or if it was obvious to you.

Let me know if I can help with anything (considering I have very limited knowledge in node and js again). 
Thanks!

**Comment by gravis** [comment]
Thanks for the fix @simonbrowndotje!  
Unfortunately, I've tested the new version and have a lot of random timeouts locally now.

As you can see here: https://gitlab.com/gitlab-com/gl-security/security-architecture/gitlab-architecture/-/jobs/5514429321, the job is failing while it was running "fine" (except the random exports) yesterday with the previous version: https://gitlab.com/gitlab-com/gl-security/security-architecture/gitlab-architecture/-/jobs/5512704106

The timeout occurs when waiting for the diagram to be rendered here:

https://github.com/structurizr/puppeteer/blob/cf6f70da15fb18c038e052c9335970eecd77025a/export-diagrams.js#L100C2-L100C2

Could it be a problem with a callback function like https://github.com/structurizr/ui/commit/3b8265fa39f3890bb1df425d8b782e5fadeaca5a#diff-92531c168674d3df419d900f58039156ebf075abfcbd2d68ea364d6ed2ac9abeR905 which would prevent `diagramRendered` to be set to `true`?

**Comment by gravis** [comment]
> Unfortunately, I've tested the new version and have a lot of random timeouts locally now.

By that, I mean some exports work, but some others timeout like the jobs in the pipelines in my previous comment. When it times out, it's always on the first diagram to be exported. If this one goes fine, the rest of the export goes smoothly.

**Comment by gravis** [comment]
I don't know if some other changes were pushed in the meantime, but exports are working fine today. Thanks again for your time and help.
