### ISSUE TITLE
Script is stuck if popup is open for informing diagram contains large number of elements / relantionships

### ISSUE THREAD

**Issue by juanrferia** [structurizr/puppeteer#8]
If a diagram contains a large number of elements / relantionships, function `structurizr.scripting.changeView` opens a popup like this:
![image](https://user-images.githubusercontent.com/11686949/158990175-a8228d0d-4cc8-4fc8-9915-e48d9a08a2f1.png)

Then the process is stuck and cannot finish.

Tested with script for Structurizr Lite, but probably impacted also in others.

**Comment by simonbrowndotje** [comment]
The best solution would be to reduce the number of elements/relationships on the diagram, but you can set a view configuration property to increase the limits though, as follows:

```
    views {
        properties {
            "structurizr.maximumElements" "200"
            "structurizr.maximumRelationships" "200"
        }

        ...
```

**Comment by juanrferia** [comment]
Yeah, I agree with you, but sometimes I cannot ensure I can reduce as I would like. 
That solution works. Thanks a lot!
